# Default build settings
[build]
  command = "./scripts/netlify-build.sh"
  functions = "dist/netlify"
  publish = ""
  environment = { CI = "true" }

# With this, the app has full control over the routing logic
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200